#!/bin/bash

if [[ -z "$GCR_PROJECT_ID" ]]; then
  echo "GCR_PROJECT_ID is not set"
  exit 1
fi

if [[ -z "$IMAGE_TAG" ]]; then
  echo "IMAGE_TAG is not set"
  exit 1
fi

for service in cms
do
  tagged=$service:$IMAGE_TAG

  echo
  echo "***** Building "$tagged' *****'
  echo
  docker build -t $tagged -f docker/deploy/$service/Dockerfile .
  gcr_tagged=gcr.io/$GCR_PROJECT_ID/$tagged

  echo
  echo "***** Pushing '$tagged' -> '$gcr_tagged' *****"
  echo
  docker tag $tagged $gcr_tagged
  docker push $gcr_tagged

  echo
done
