version: '3.8'

services:
  db:
    container_name: tf-fullstack-db
    image: postgres:13-alpine
    environment:
      # The postgres image automatically uses these variables to create the database and user
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5555:5432
