version: '3.8'

services:
  db:
    container_name: fullstack-tf-db
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5555:5432

  migrate:
    container_name: fullstack-tf-migrate
    build:
      context: ./api
    environment:
      - SQLALCHEMY_URL=postgresql://user:password@db:5432/mydb
    entrypoint: ["alembic", "upgrade", "head"]

  api:
    container_name: fullstack-tf-api
    build:
      context: ./api
    environment:
      - SQLALCHEMY_URL=postgresql://user:password@db:5432/mydb
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - 8000:8000

  task:
    container_name: fullstack-tf-api
    container_name: fullstack-tf-task
    build:
      context: ./task
    environment:
      - SQLALCHEMY_URL=postgresql://user:password@db:5432/mydb

  web:
    container_name: fullstack-tf-api
    container_name: fullstack-tf-web
    build:
      context: ./web
    environment:
      - API_URL=http://api:8000
      - HOST=0.0.0.0
      - PORT=8001
    ports:
      - 8001:8001
