#!/bin/bash

if [[ -z "$GCR_KEY_FILE" ]]; then
    echo "GCR_KEY_FILE is not set"
    exit 1
fi

if [[ -z "$GCR_PROJECT_ID" ]]; then
    echo "GCR_PROJECT_ID is not set"
    exit 1
fi

# Authenticate via JSON key file
# https://cloud.google.com/container-registry/docs/advanced-authentication#json-key
cat $GCR_KEY_FILE | docker login -u _json_key --password-stdin https://gcr.io

docker-compose build

for service in api task web
do
    image=fullstack_$service:latest
    retag=gcr.io/$GCR_PROJECT_ID/$image

    echo "Pushing '$image' -> '$retag'"

    docker tag $image $retag
    docker push $retag

    echo
done
