#!/bin/bash

if [[ -z "$GCR_KEY_FILE" ]]; then
    echo "GCR_KEY_FILE is not set"
    exit 1
fi

if [[ -z "$GCR_PROJECT_ID" ]]; then
    echo "GCR_PROJECT_ID is not set"
    exit 1
fi

# Authenticate via JSON key file
# https://cloud.google.com/container-registry/docs/advanced-authentication#json-key
cat $GCR_KEY_FILE | docker login -u _json_key --password-stdin https://gcr.io

# Append a timestamp to images for a basic tag, otherwise
# using 'latest' won't force a new Cloud Run revision
timestamp=$( date +%s )

docker-compose build

for service in api task web
do
    image=fullstack_$service
    retag=gcr.io/$GCR_PROJECT_ID/$image:$timestamp

    echo "Pushing '$image:latest' -> '$retag'"

    docker tag $image:latest $retag
    docker push $retag

    echo
done
